"""Generate mod/src/ScalarFields.inc from the Geode bindings.

Emits the plain-value members of the classes a snapshot restore carries, as
offsetof/sizeof spans with a parallel table of names. A snapshot restore copies
exactly these bytes back, so the tables must never admit a pointer or a
container: copying one by bytes corrupts the heap (gdsolver hit exactly this) or
aliases state the restore does not own. Admission is therefore by TYPE, from an
allow-list:

  - built-in arithmetic types and bool
  - cocos value structs: CCPoint, CCSize, CCRect, ccColor3B, ccHSVValue
  - enums known to be plain: see ENUMS

Everything else is rejected and listed on stderr, so a new member type in a new
bindings version is seen rather than silently copied.

Platform blocks ("android, ios { ... }") hold members that do not exist in the
Windows layout and are skipped unless they name win.

Tables:
  kPlayerScalarFields    PlayerObject, with GameObject's members addressed
                         through GameObject (see below)
  kObjectScalarFields    GameObject
  kEnhancedScalarFields  EnhancedGameObject's own members
  kEffectScalarFields    EffectGameObject's own members (orbs, pads, portals,
                         triggers are EffectGameObjects)
  kRingScalarFields      RingObject's own members
  kLayerScalarFields     GJBaseGameLayer's own members
  kPlayLayerScalarFields PlayLayer's own members
Each has a parallel <name>Names array of "Class::m_member" strings.

Usage: python tools/gen_scalar_fields.py <bindings dir> > mod/src/ScalarFields.inc
"""
import re
import sys

BUILTIN = {
    "bool", "char", "short", "int", "long", "float", "double",
    "unsigned", "unsigned char", "unsigned short", "unsigned int", "unsigned long",
    "int8_t", "int16_t", "int32_t", "int64_t",
    "uint8_t", "uint16_t", "uint32_t", "uint64_t",
}
COCOS = {"cocos2d::CCPoint", "cocos2d::CCSize", "cocos2d::CCRect",
         "cocos2d::ccColor3B", "cocos2d::ccHSVValue"}
ENUMS = {"GameObjectType", "ZLayer", "GameObjectClassType", "GhostType", "ShipStreak",
         "TouchTriggerType", "TouchTriggerControl", "PlaybackMode", "MoveTargetType",
         "EasingType"}


def members(bro_text, cls):
    m = re.search(r"^class %s\b[^\n]*$(.*?)^\}" % re.escape(cls), bro_text, re.S | re.M)
    if not m:
        sys.exit("class %s not found" % cls)
    out, skipping = [], False
    for raw in m.group(1).splitlines():
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        pb = re.match(r"^([a-z0-9_]+(?:\s*,\s*[a-z0-9_]+)*)\s*\{$", line)
        if pb:
            plats = [p.strip() for p in pb.group(1).split(",")]
            skipping = "win" not in plats
            continue
        if line == "}":
            skipping = False
            continue
        if skipping or "(" in line or not line.endswith(";"):
            continue
        decl = line[:-1].strip()
        mm = re.match(r"^(.*?)\s*\b(m_[A-Za-z0-9_]+)$", decl)
        if not mm:
            continue
        out.append((mm.group(1).strip(), mm.group(2)))
    return out


# Members never carried even though their type is plain. m_varianceIndex is a
# display value GD re-randomises on every full reset: carried, every fallback
# restore made every object differ from the snapshot baseline, and snapshots grew
# from ~26-90 KB to the whole world (~430 KB on Clubstep).
DENY = {"m_varianceIndex"}


def admit(t):
    if "*" in t or "&" in t or "<" in t:
        return False
    return t in BUILTIN or t in COCOS or t in ENUMS


def main():
    d = sys.argv[1]
    text = open(d + "/GeometryDash.bro", encoding="utf-8").read()
    cls = {c: members(text, c) for c in
           ("GameObject", "PlayerObject", "EnhancedGameObject", "EffectGameObject",
            "RingObject", "GJBaseGameLayer", "PlayLayer", "GJGameState", "GJEffectManager")}

    def emit(name, groups):
        spans, names, rejected = [], [], []
        for owner, fields in groups:
            for t, n in fields:
                if admit(t) and n not in DENY:
                    spans.append("\t{offsetof(%s, %s), sizeof(%s::%s)},   // %s" % (owner, n, owner, n, t))
                    names.append('\t"%s::%s",' % (owner, n))
                else:
                    rejected.append("%s %s::%s" % (t, owner, n))
        print("static const PlayerFieldSpan %s[] = {" % name)
        print("\n".join(spans))
        print("};")
        print("static const char* const %sNames[] = {" % name)
        print("\n".join(names))
        print("};")
        print()
        sys.stderr.write("%s: %d kept, %d rejected\n" % (name, len(spans), len(rejected)))
        for r in rejected:
            sys.stderr.write("    rejected %s\n" % r)

    print("// Generated by tools/gen_scalar_fields.py from bindings/2.2081 - do not edit.")
    print("// Plain-value members only: see the script for the admission rule.")
    print()
    # GameObject's members go through GameObject even in the player table: a
    # member PlayerObject redeclares (m_unk50C) would otherwise hide the base's,
    # and offsetof(PlayerObject, m_unk50C) would name only the derived one.
    # Valid because GameObject is PlayerObject's first base, at offset 0 -
    # checked at run time by the mod before the table is used.
    emit("kPlayerScalarFields", [("GameObject", cls["GameObject"]),
                                 ("PlayerObject", cls["PlayerObject"])])
    emit("kObjectScalarFields", [("GameObject", cls["GameObject"])])
    emit("kEnhancedScalarFields", [("EnhancedGameObject", cls["EnhancedGameObject"])])
    emit("kEffectScalarFields", [("EffectGameObject", cls["EffectGameObject"])])
    emit("kRingScalarFields", [("RingObject", cls["RingObject"])])
    emit("kLayerScalarFields", [("GJBaseGameLayer", cls["GJBaseGameLayer"])])
    emit("kPlayLayerScalarFields", [("PlayLayer", cls["PlayLayer"])])
    emit("kGameStateScalarFields", [("GJGameState", cls["GJGameState"])])
    emit("kEffectManagerScalarFields", [("GJEffectManager", cls["GJEffectManager"])])

    # Container sizes, for diffing: a snapshot that leaves a set, map or array
    # with a different size than the full restore does is missing that state.
    def is_container(t):
        return re.match(r"^(gd|std)::(vector|unordered_map|unordered_set|map|set|string)\b", t) is not None

    def is_ccarray(t):
        return t in ("cocos2d::CCArray*", "cocos2d::CCDictionary*")

    print("template <class Out>")
    print("static void scalarContainerSizes(PlayerObject* p, GJBaseGameLayer* l, PlayLayer* pl, GJEffectManager* em, GJGameState* gs, Out&& out) {")
    for owner, var in (("PlayerObject", "p"), ("GJBaseGameLayer", "l"), ("PlayLayer", "pl"), ("GJEffectManager", "em"), ("GJGameState", "gs")):
        print("	if (%s) {" % var)
        for t, n in cls[owner]:
            if is_container(t):
                print('		out("%s::%s", static_cast<long long>(%s->%s.size()));' % (owner, n, var, n))
            elif is_ccarray(t) and 'unk' not in n.lower():
                chk = (' && %s->%s->data' % (var, n)) if t == 'cocos2d::CCArray*' else ''
                print('		out("%s::%s", (%s->%s%s) ? static_cast<long long>(%s->%s->count()) : -1LL);' % (owner, n, var, n, chk, var, n))
        print("	}")
    print("}")


if __name__ == "__main__":
    main()
